### ISSUE TITLE
Make shitter able to recieve a number a print the corresponding sheet

### ISSUE THREAD

**Issue by ygneo** [alexavenger/shitter#5]
Shitter should be able to recieve a number and locate (within the hardcoded WORKSPACE and FOLDER), the corresponding sheet, or an error message if not found or there are more than one sheet starting with that number.

Once the sheet is located, print all its attributes.

Use python split function to find the sheet.

**Comment by alexavenger** [comment]
I think this is done.

Now when running ./shiter.py we can add an argument --> ./shitter.py 1
this 1 means the sheet number 1. 
Then the program is first checking that this sheet exists.
If exists it print the whole sheet.
If not it shows you the text saying this sheet doesn't exist.
